### PR TITLE
Here is my contribution

### PR DESCRIPTION
**Pull request by movarnell**
Hey Chris,
I have a student doing this with me in a session, so you can't delete it for hating on Apple. LOL

Great project!

### CODE REVIEW

**Review by ConwayCJ — CHANGES_REQUESTED** [review]
Please limit the prompt to 3 words + more ambiguous answer

**Review by movarnell — COMMENTED** [review]
Reviewed, and changed to meet criteria, isn't the best puzzle, but neither was the original!

**Review by ConwayCJ — CHANGES_REQUESTED** [review]
Add additional emojis

**Comment by movarnell** [comment]
I have added 3 puzzles and verified their function. Submitting for merge.

**Comment by ConwayCJ** [comment]
Hey Michael, I changed a lot of the requirements because of formatting issues. Can you limit the prompts to 3 words or just remove the last one?

**Comment by movarnell** [comment]
Pushed up with required changes as requested. Fingers crossed this one works well with the current implementation.

**Comment by ConwayCJ** [comment]
Looks great, thanks!

**Pull request merged**
